### ISSUE TITLE
Support for WebGL builds

### ISSUE THREAD

**Issue by justinduynguyen** [itisnajim/SocketIOUnity#3]
May you implement a version for WebGL or intent to do in future? I

**Comment by itisnajim** [comment]
Maybe if this (issue) got more votes :)

**Comment by nekiwo** [comment]
Is the issue with `socket.io-client-csharp` being not compatible with WebGL or this library's implementation?

**Comment by nekiwo** [comment]
Okay I found the incompatible code. The issue was inside `socket.io-client-csharp` and not the `SocketIOUnity` implementation.

[`SocketIOClient/Transport/HttpTransport.cs`](https://github.com/itisnajim/SocketIOUnity/blob/5106ed6444ca7bf8f55d64f5fb62ce01809a97e8/Runtime/SocketIOClient/Transport/HttpTransport.cs) Uses the .NET library `system.net.http`, which is [incompatible with WebGL](https://stackoverflow.com/questions/50160380/difference-between-httpclient-and-unitys-unitywebrequest-www-api)
Adding WebGL support should be as simple as implementing `UnityWebRequest` instead of `HttpClient`.

**Comment by itisnajim** [comment]
socket.io-client-csharp its not for a web project, needs a bridge so!

**Comment by nekiwo** [comment]
Another issue:  `socket.io-client-csharp` uses threads which [aren't compatible with WebGL Unity builds yet](https://forum.unity.com/threads/multithreading-and-webgl.817986/)

**Comment by benji56** [comment]
I guess you don't see any possibility of it ever being compatible?

**Comment by itisnajim** [comment]
> I guess you don't see any possibility of it ever being compatible?

I'm sorry, but the `socket.io-client-csharp` package is not compatible with the web. However, you can search for a web unity socket io package or create your own, check out [Unity-WebGL-3D-Chat](https://github.com/hecomi/Unity-WebGL-3D-Chat) . And combine it with [this](https://github.com/itisnajim/SocketIOUnity) package using an IF ELSE statement.

You can create two separate classes: one for web called `SocketIOWebManager` and one for native called `SocketIONativeManager`, and another class to communicate with one of the two depending on the current platform. You can do something similar to what is shown in the [SocketManager](https://github.com/itisnajim/SocketIOUnity/blob/main/Samples~/Sample/SocketManager.cs) file, where in the start method you can check the current platform and start either the `SocketIOWebManager` or `SocketIONativeManager` object.

I hope this helps!

**Comment by winxinxinxin** [comment]
hope webgl support

**Comment by nekiwo** [comment]
For those still looking for an answer, making a JS plug-in that calls socket.io seems to be the only way for now, although this solution isn't ideal.

**Comment by LesBonsOeufs** [comment]
@nekiwo Any news on this JS plug-in?
