### ISSUE TITLE
Hololens 2 Socket IO connection not working

### ISSUE THREAD

**Issue by ThimoDEV** [itisnajim/SocketIOUnity#6]
Currently I'm working on an application for the Hololens 2. 

I created a small NodeJS server which watches a folder for new added files. This server then sends with Socket IO this data to the Unity client. This works perfectly in the editor. However, When I have a build on my Hololens 2. The application doesn't want to connect to my pc.

- I made sure I'm on the same network.
- I enabled all build settings capabilities

Steps to reproduce:

- Create a simple server with the Socket IO installed
- Create a Unity client that connects to this server.
- Make sure all capabilities are toggled in build settings
- Build the Unity application to the UWP hololens 2
- socket.Connected shows false when app launched on hololens UWP.

Do you know what might cause this issue or how I can solve it?

many thanks

**Comment by itisnajim** [comment]
Hello ThimoDev, 

Have you tried using http pool transport instead of websocket and setting AutoUpgrade to false (AutoUpgrade default value is true If websocket is available, it will be automatically upgrade to use websocket)
see: 
https://github.com/doghappy/socket.io-client-csharp#options
https://stackoverflow.com/a/40805832

Hope this is helpful.

**Comment by ThimoDEV** [comment]
I found out there was a problem in our offices network security. After disabling that it worked. Thank you for all your help!
